# This file was generated by GoReleaser. DO NOT EDIT.
cask "s9l" do
  version "0.11.0"

  on_macos do
    on_intel do
      sha256 "f48f96f1410b396e807e0108ba3944c1c95f4bb6e23099304e9f5c21b016e169"
      url "https://github.com/YangXplorer/s9l/releases/download/v#{version}/s9l_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8cb0f920798ad17b5d1463e1e8781c408302cdfe014b08604f364ecae9a0d62f"
      url "https://github.com/YangXplorer/s9l/releases/download/v#{version}/s9l_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7faca85bd21d186dc632f4e8f78088b1340f8605b08f9be5691b98212f517d18"
      url "https://github.com/YangXplorer/s9l/releases/download/v#{version}/s9l_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f3787765e5f6c165b8378cb82d67cc9afb1d404a67cfb373cad9d20dd9c7400f"
      url "https://github.com/YangXplorer/s9l/releases/download/v#{version}/s9l_#{version}_linux_arm64.tar.gz"
    end
  end

  name "s9l"
  desc "Fast terminal database client (SQLite, PostgreSQL, MySQL) with a TUI"
  homepage "https://github.com/YangXplorer/s9l"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "s9l"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/s9l"]
    end
  end

  # No zap stanza required

end
