# This file was generated by GoReleaser. DO NOT EDIT.
cask "s9l" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "1f7bd7ab34cdbdf537256290c2a5e01fd52b5015a5b89558bc1a7676f0a8b76a"
      url "https://github.com/YangXplorer/s9l/releases/download/v#{version}/s9l_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "759bc6e17d0d426eda6d5e312747958b4fe387f9db0c75bb7cac9bd83f8a83a5"
      url "https://github.com/YangXplorer/s9l/releases/download/v#{version}/s9l_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d0e546368cb94b2e70da65ef49804843a5b96b61d5a04e56c81a8f054b12222f"
      url "https://github.com/YangXplorer/s9l/releases/download/v#{version}/s9l_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d6d19a7dc7bd8d522bc494978cf6fede269b29ccc5df978a5fbf3c3015371be8"
      url "https://github.com/YangXplorer/s9l/releases/download/v#{version}/s9l_#{version}_linux_arm64.tar.gz"
    end
  end

  name "s9l"
  desc "Fast terminal database client (SQLite, PostgreSQL, MySQL) with a TUI"
  homepage "https://github.com/YangXplorer/s9l"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "s9l"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/s9l"]
    end
  end

  # No zap stanza required

end
