# This file was generated by GoReleaser. DO NOT EDIT.
cask "s9l" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "aff09efcced0874a35cd5d1be24f32b24fddb5fbf2dd3c885783b22a8e1930bd"
      url "https://github.com/YangXplorer/s9l/releases/download/v#{version}/s9l_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5aa0f2d0d67c129668385f75524085dcd655f2902b5fb6a1434c5d237eae2fa4"
      url "https://github.com/YangXplorer/s9l/releases/download/v#{version}/s9l_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "96c8d7a5fd1f0e4f661532f715461f407e5e2fd212ccd8610cdc477440733dc9"
      url "https://github.com/YangXplorer/s9l/releases/download/v#{version}/s9l_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4aa08b861fec53aee58528f7073e1110e0d5b4f6ec51255feaf6b64f5614a4fc"
      url "https://github.com/YangXplorer/s9l/releases/download/v#{version}/s9l_#{version}_linux_arm64.tar.gz"
    end
  end

  name "s9l"
  desc "Fast terminal database client (SQLite, PostgreSQL, MySQL) with a TUI"
  homepage "https://github.com/YangXplorer/s9l"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "s9l"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/s9l"]
    end
  end

  # No zap stanza required

end
